library(caTools)
data <- read.csv("R_Vraag_1.csv")
data$title <- NULL
split = sample.split(data$rating, SplitRatio = .65)
train = subset(data, split==TRUE)
test = subset(data, split==FALSE)
model <- lm(rating~seasons, data = train)
pred <- predict(model, newdata = test)
plot(test$seasons, test$rating, col = "blue", xlab = "Seasons", ylab = "Rating")
points(pred, col = "red")